name: ${COMPOSE_PROJECT_NAME:-revenger_devcontainer}

version: '3'
services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    environment:
      PORT: ${PORT:-3000}
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    volumes:
      - ../..:/workspaces:cached
      - bundle:/usr/local/bundle
volumes:
  bundle:
